config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :students
  resources :courses
  resources :classrooms

  root "welcome#index"

  get 'subscribes' => 'subscribes#index'
  post 'subscribes' => 'subscribes#save'










end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	has_many :students
	belongs_to :course
end

app/models/course.rb
class Course < ActiveRecord::Base
	validates :name, presence: true, length: {minimum: 5, maximum: 25}
	validates :description, presence: true 
	validates :status,  presence: true

	belongs_to :classroom
end

app/models/student.rb
class Student < ActiveRecord::Base
	validates :name, presence: true, length: {minimum: 5, maximum: 25}
	validates :register_number,  presence: true
	validates :status,  presence: true

	belongs_to :classroom
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@classrooms = Classroom.all.page(params[:page]).per(5)
	end
	
	def new
		@courses = Course.select("name", "id")
		@classroom = Classroom.new
	end

	def show
		@classroom = Classroom.find(params[:id])
		studentsId = @classroom.student_id
		@students = []
		studentsId.each do |s|
			@students <= s.name
		end
	end

	def create
		@classroom = Classroom.new(classroom_params)

		if @classroom.save
			redirect_to @classroom
		else
			render 'new'
		end
	end

	def edit
		@classroom = Classroom.find(params[:id])
	end

	def update
		@classroom = Classroom.find(params[:id])

		if @classroom.update(params[:classroom].(:entry_at, :course_id, :student_id))
			redirect_to @classroom
		else
			render 'edit'
		end
	end

	def destroy
		@classroom = Classroom.find(params[:id])
		@classroom.destroy

		redirect_to classrooms_path
	end

	private

	def classroom_params
		params.require(:classroom).permit(:entry_at, :course_id, :student_id)
	end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@courses = Course.all.page(params[:page]).per(5)
	end
	
	def new
		@course = Course.new
	end

	def show
		@course = Course.find(params[:id])
	end

	def create
		@course = Course.new(course_params)

		if @course.save
			redirect_to @course
		else
			render 'new'
		end
	end

	def edit
		@course = Course.find(params[:id])
	end

	def update
		@course = Course.find(params[:id])

		if @course.update(params[:course].permit(:name, :register_number, :status))
			redirect_to @course
		else
			render 'edit'
		end
	end

	def destroy
		@course = Course.find(params[:id])
		@course.destroy

		redirect_to courses_path
	end

	private

	def course_params
		params.require(:course).permit(:name, :description, :status)
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@students = Student.all.page(params[:page]).per(5)
	end

	def new
		@student = Student.new
	end

	def show
		@student = Student.find(params[:id])
	end

	def create
		@student = Student.new(student_params)

		if @student.save
			redirect_to @student
		else
			render 'new'
		end
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
		@student = Student.find(params[:id])

		if @student.update(params[:student].permit(:name, :register_number, :status))
			redirect_to @student
		else
			render 'edit'
		end
	end

	def destroy
		@student = Student.find(params[:id])
		@student.destroy

		redirect_to students_path
	end

	private

	def student_params
		params.require(:student).permit(:name, :register_number, :status)
	end
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController
	def index
		@classrooms = Classroom.select(:id, :name).joins(:course)
		@students = Student.all
	end
	
	def save
		@classroom = Classroom.find(1)
		student = Student.find(1)
		@classroom.student_id[@classroom.student_id.size] = student.id
		@classroom.entry_at[@classroom.entry_at.size] = Date.current
		if @classroom.save
			redirect_to @classroom
		else
			render 'index'
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/_form.html.erb
<%= form_for @classroom do |f| %>
	<% if @classroom.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@classroom.errors.count, "error") %> prevented this classroom from saving:</h2>
			<ul>
				<% @classroom.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<%= f.label :course_id, "Curso" %><br>
	<%= f.collection_select :course_id, @courses,:id,:name, {},class:"form-control" %>
	<br>

	<%= f.submit "Ok", class: "btn btn-success" %>
<% end %>

app/views/classrooms/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Editar turma</div>
  	<div class="panel-body">
		<%= render 'form' %>
	</div>
  </div>
</div>

app/views/classrooms/index.html.erb
<h2>Turmas<%= link_to 'Criar', new_classroom_path, class:"btn btn-success pull-right" %></h2>
<br>
<table class="table table-hover">
	<tr>
		<th>Turma</th>
		<th>Curso</th>
		<th>Ações</th>
		<th></th>
	</tr>
	<% @classrooms.each do |classroom| %>
	<tr>
		<th><%= link_to classroom.id, classroom, class:"btn btn-link" %></th>
		<th><%= classroom.course.name %></th>
		<th><%= link_to 'Editar', edit_classroom_path(classroom) %></th>
		<th><%= link_to 'Excluir', classroom_path(classroom), method: :delete, data: { confirm: 'Are you sure?', class:'btn btn-link' } %></th>
	</tr>
	<% end %>
</table>
<%= paginate @classrooms, theme:"twitter-bootstrap-3" %>

app/views/classrooms/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Nova turma</div>
  	<div class="panel-body">
		<%= render 'form' %>
	</div>
  </div>
</div>

app/views/classrooms/show.html.erb
<div class="col-md-2"></div>
<div class="col-md-8">
	<div class="panel panel-default">
	  <div class="panel-heading"><%=@classroom.course.name %></div>
	  	<div class="panel-body">
			<p class="status">Turma: <%= @classroom.id %></p>
			<p class="actions">
				<%= link_to 'Editar', edit_classroom_path(@classroom), class:'btn btn-primary pull-left' %>
				<%= link_to 'Excluir', classroom_path(@classroom), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger pull-right' %>
			</p>
			<% if !@students[0] == nil %>
				<% @students.each do |s| %>
					<%= s.name %>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
	<% if @course.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@course.errors.count, "error") %> prevented this course from saving:</h2>
			<ul>
				<% @course.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<%= f.label :name, "Nome" %><br>
	<%= f.text_field :name, placeholder:"Digite o nome do curso", required:"", class:"form-control" %>
	<br>

	<%= f.label :status, "Status" %><br>
	<%= f.number_field :status, placeholder:"Digite o status do curso", required:"", class:"form-control" %>
	<br>

	<%= f.label :description, "Descrição" %><br>
	<%= f.text_area :description, placeholder:"Digite a descrição do curso", required:"", class:"form-control" %>

	<br>
	
	<%= f.submit "Ok", class: "btn btn-success" %>
<% end %>

app/views/courses/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Editar curso</div>
  	<div class="panel-body">
		<%= render 'form' %>
	</div>
  </div>
</div>

app/views/courses/index.html.erb
<h2>Cursos <%= link_to 'Criar', new_course_path, class:"btn btn-success pull-right" %></h2>
<br>
<table class="table table-hover">
	<tr>
		<th>Nome</th>
		<th>Status</th>
		<th>Ações</th>
		<th></th>
	</tr>
	<% @courses.each do |course| %>
	<tr>
		<th><%= link_to course.name, course, class:"btn btn-link" %></th>
		<th><%= course.status %></th>
		<th><%= link_to 'Editar', edit_course_path(course) %></th>
		<th><%= link_to 'Excluir', course_path(course), method: :delete, data: { confirm: 'Are you sure?', class:'btn btn-link' } %></th>
	</tr>
	<% end %>
</table>
<%= paginate @courses, theme:"twitter-bootstrap-3" %>

app/views/courses/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Novo curso</div>
  	<div class="panel-body">
		<%= render 'form' %>
	</div>
  </div>
</div>

app/views/courses/show.html.erb
<div class="col-md-2"></div>
<div class="col-md-8">
	<div class="panel panel-default">
	  <div class="panel-heading"><%= @course.name %></div>
	  	<div class="panel-body">
			<p class="status">Status: <%= @course.status %></p>
			<p class="description">Descrição: <%= @course.description %></p>
			<p class="actions">
				<%= link_to 'Editar', edit_course_path(@course), class:'btn btn-primary pull-left' %>
				<%= link_to 'Excluir', course_path(@course), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger pull-right' %>
			</p>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProficiencyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="http://lvh.me:3000/">Internet Sistemas</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="http://lvh.me:3000/students/">Alunos</a></li>
            <li><a href="http://lvh.me:3000/courses/">Cursos</a></li>
            <li><a href="http://lvh.me:3000/classrooms/">Turmas</a></li>
            <li><a href="http://lvh.me:3000/subscribes/">Matrícula</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if !user_signed_in? %>
              <li><a href="http://lvh.me:3000/users/sign_in">Acessar sua conta</a></li>
              <li><a href="http://lvh.me:3000/users/sign_up">Criar uma conta</a></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    
    <br><br><br><br>
<div class="col-md-2"></div>
<div class="col-md-8">
<%= yield %>
</div>
<div class="col-md-2"></div>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
	<% if @student.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@student.errors.count, "error") %> prevented this student from saving:</h2>
			<ul>
				<% @student.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<%= f.label :name, "Nome" %><br>
	<%= f.text_field :name, placeholder:"Digite o nome do aluno", required:"", class:"form-control" %>
	<br>
	
	<br>

	<%= f.label :register_number, "Número de registro" %><br>
	<%= f.text_field :register_number, placeholder:"Digite o número de registro do aluno", required:"", class:"form-control", id:"register_number" %><br>
	
	<br>

	<%= f.label :status, "Status" %><br>
	<%= f.text_field :status, placeholder:"Digite o status do aluno", required:"", class:"form-control", id:"status" %><br>

	<%= f.submit "Ok", class: "btn btn-success" %>
<% end %>

app/views/students/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Editar aluno</div>
  	<div class="panel-body">
		<%= render 'form' %>
	</div>
  </div>
</div>

app/views/students/index.html.erb
<h2>Estudantes <%= link_to 'Criar', new_student_path, class:"btn btn-success pull-right" %></h2>
<br>
<table class="table table-hover">
	<tr>
		<th>Nome</th>
		<th>Número de registro</th>
		<th>Status</th>
		<th>Ações</th>
		<th></th>
	</tr>
	<% @students.each do |student| %>
	<tr>
		<th><%= link_to student.name, student, class:"btn btn-link" %></th>
		<th><%= student.register_number %></th>
		<th><%= student.status %></th>
		<th><%= link_to 'Editar', edit_student_path(student) %></th>
		<th><%= link_to 'Excluir', student_path(student), method: :delete, data: { confirm: 'Are you sure?', class:'btn btn-link' } %></th>
	</tr>
	<% end %>
</table>
<%= paginate @students, theme:"twitter-bootstrap-3" %>

app/views/students/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Novo aluno</div>
  	<div class="panel-body">
		<%= render 'form' %>
	</div>
  </div>
</div>

app/views/students/show.html.erb
<div class="col-md-2"></div>
<div class="col-md-8">
	<div class="panel panel-default">
	  <div class="panel-heading"><%= @student.name %></div>
	  	<div class="panel-body">
			<p class="register_number">Número de registro: <%= @student.register_number %></p>
			<p class="status">Status: <%= @student.status %></p>
			<p class="actions">
				<%= link_to 'Editar', edit_student_path(@student), class:'btn btn-primary pull-left' %>
				<%= link_to 'Excluir', student_path(@student), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger pull-right' %>
			</p>
		</div>
	</div>
</div>

app/views/subscribes/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Selecione uma turma</div>
  	<div class="panel-body">
		<%= form_tag '/subscribes', multipart: true do %>
			<label>Turma</label><br>
			<%= select_tag :id, options_from_collection_for_select(@classrooms, "id", "name"), class:"form-control" %>
			<br>
			<label>Aluno</label><br>
			<%= select_tag :id, options_from_collection_for_select(@students, "id", "name"), class:"form-control" %>
			<br>
			<%= submit_tag "Adicionar", controller:"subscribes", action:"save", class:"btn btn-success" %>
		<% end %>
	</div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Internet Sistemas</h1>

<p><b>

Internet Sistemas | Especialistas em sistemas web.

</b></p>
<p>
Apaixonados por desafios, nossa missão é inovar! Trabalhando em sistemas utilizando a WEB como plataforma, a Internet Sistemas atua no mercado a 10 anos. Inovando e criando soluções tecnológicas personalizadas a sua empresa.
</p>
<p><b>Treinamentos</b></p>
<p>
Depois do sucesso de 2010, a Internet Sistemas amplia seus cursos de Webdesign, Programação, PHP e palestras para 2011!
Clique aqui e saiba mais detalhes!
</p>